version: '3.3'

services:
  vliller-elasticsearch:
    container_name: vliller-elasticsearch
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    networks:
      - default
      - vlillernet
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - DOCKUID=${UID} # UID define in .env
      - DOCKGID=${UID} # UID define in .env

  # vliller-kibana:
  #   container_name: vliller-kibana
  #   restart: unless-stopped
  #   image: docker.elastic.co/kibana/kibana:6.4.2
  #   networks:
  #     - default
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - vliller-elasticsearch
  #   # volumes:
  #     # - /etc/localtime:/etc/localtime:ro
  #     # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  #   environment:
  #     - DOCKUID=${UID} # UID define in .env
  #     - DOCKGID=${UID} # UID define in .env
  #     - ELASTICSEARCH_URL=http://vliller-elasticsearch:9200

  vliller-miners:
    container_name: vliller-miners
    image: vliller-miners
    networks:
      - default
      - vlillernet
    depends_on:
      - vliller-elasticsearch

    # keeps container awake
    stdin_open: true
    tty: true

networks:
  vlillernet:
    external: true

